time-displayed = The time displayed is European Time. (GMT+2)
no-information = There isn't much information to show here...
done = Done
complete = Complete
no-result-found = No result was found.
option = Option
options = Options
setting = Setting
settings = Settings

missing-perm = I lack the following permissions to function properly:
missing-channel = I don't find this channel.
missing-role = I don't find this role.

wait-bot-to-finish-startup = Please wait the bot from finishing startup...

reply-failed-not-guild = This is not a guild.
reply-failed-not-in-guild = This command can only be done in a guild.

warn-missing-permissions = :warning: The bot lacks some permissions to work properly: `<v1>` on **<v2>**.
warn-bad-permissions = :warning: It appears that the bot currently has some dangerous redundant permissions on **<v2>**.<br>Make sure the bot doesn't have these permissions: `<v1>`.<br>If you still don't find them, check Bot roles, it is a bad practice for server moderators to give all permissions to bots. :wink:
wrong-channel-type-text = You need to select a **text channel**.
error-invalid-invite-link = This is an invalid invite link.
error-invalid-url-link = This is an invalid url.

error-illegal-character = [Error] Contains illegal words or characters such as -->  \ | : *? " < >.
error-invalid-colorcode = [Error] Please write a VALID Hexadecimal color code ---> "#000000"
error-invalid-emoji = [Error] Please write a VALID single emoji or Unicode.
error-invalid-date = [Error] Please write a valid date of format dd/MM/yyyy.

error-already-exist-or-similar = [Error] Failed to set <v1>, <v1> already exist or is too similar to another <v1>.

error-dm-not-open = [Error] Your DMs are not open.
authAccountUser-not-part-of-guild = <v1> is not part of this guild. Please invite them here first.

file-ready = Your file(s) are ready for Download!
file-ready-fail = Failed to produce your file. Try again or re-write the command.
image-fail-extension = This file is not a **PNG Image**. Try again.
image-fail-url = This URL doesn't point to anything... Try again.
image-fail-png = This should not be a full image. It should have a transparent background.

reply-failed-not-enough-permission-you = You don't have the permission for this action: Permission.<v1>

role-create = Creating new role <v1>.
role-icon-success = Role icon of <v1> role has been changed.
role-delete-success = The role <v1> has been deleted.
role-rename-success = Modified the role name of <v1> to <v2>.
role-recolor-success = Modified the role color of <v1> to <v2>.
role-add-success = Added the <v1> role to <v2>.
role-remove-success = Removed the <v1> role from <v2>.
nickname-modify-success = Modified the nickname of <v1> to <v2>.

role-access-interact-fail = **[Error]** Couldn't access the <v1> role as I cannot interact with this role. Put it below my highest role.
role-rename-interact-fail = **[Error]** Couldn't rename the <v1> role as I cannot interact with this role.
role-delete-interact-fail = **[Error]** Couldn't delete the <v1> role as I cannot interact with this role.
role-recolor-interact-fail = **[Error]** Couldn't change the color of the <v1> role as I cannot interact with this role.
role-add-interact-fail = **[Error]** Couldn't give the <v1> role to <v2> as I cannot interact with this role.
role-remove-interact-fail = **[Error]** Couldn't remove <v1> role from <v2> as I cannot interact with this role.
role-icon-interact-fail = **[Error]** Couldn't change the icon of <v1> role from <v2> as I cannot interact with this role.

role-create-permission-fail = **[Error]** Couldn't create the <v1> role as I lack permissions to do so: __Permission.MANAGE_ROLES__
role-delete-permission-fail = **[Error]** Couldn't delete the <v1> role as I lack permissions to do so: __Permission.MANAGE_ROLES__
role-rename-permission-fail = **[Error]** Couldn't rename the <v1> role as I lack permissions to do so: __Permission.MANAGE_ROLES__
role-recolor-permission-fail = "**[Error]** Couldn't change the color of the <v1> role as I lack permissions to do so: __Permission.MANAGE_ROLES__
role-add-permission-fail = **[Error]** Couldn't give the <v1> role to <v2> as I lack permissions to do so: __Permission.MANAGE_ROLES__
role-remove-permission-fail = **[Error]** Couldn't remove the <v1> role to <v2> as I lack permissions to do so: __Permission.MANAGE_ROLES__
role-icon-permission-fail = **[Error]** Couldn't set the role icon of the <v1> role as I lack permissions to do so: __Permission.MANAGE_ROLES__
nickname-modify-permission-fail = **[Error]** Couldn't modify the nickname of <v1> as I lack permissions to do so: __Permission.MANAGE_NICKNAME__
nickname-modify-interact-fail = **[Error]** Couldn't modify the nickname of <v1> as I cannot interact with this member.
